name: Python-test

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
          
      - name: Python version
        run: python --version
        
      - name: List files in the repository
        run: |
          ls -l ${{github.workspace}}
        
#       - name: Hello world
#         run: python ${{github.workspace}}/test.py
    
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: java -cp java HelloWorldApp


