name: Maven CI
on: push

jobs:
  build:
    name: Setting the Ubuntu Environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-jave@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean compile install package
